# theme: jekyll-theme-cayman
# base:
#   background_color: transparent
title: Andry Rajaoberison
title_page:
  background_image: https://github.com/rajaoberison/rajaoberison.github.io/blob/master/images/marojejy.JPG
page:
  layout: portrait
  margin: [0.75in, 1in, 0.75in, 1in]
  size: Letter
base:
  font_color: #333333
  font_family: Times-Roman
  font_size: 12
  line_height_length: 17
  line_height: $base_line_height_length / $base_font_size
vertical_spacing: $base_line_height_length
heading:
  font_color: #262626
  font_size: 17
  font_style: bold
  line_height: 1.2
  margin_bottom: $vertical_spacing
link:
  font_color: #002FA7
outline_list:
  indent: $base_font_size * 1.5
